version: "3.7"

services:
  db:
    image: postgres
    env_file:
      - pg.dev.env

  web:
    build: 
      context: .
      dockerfile: Dockerfile.web
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - dev.env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    command: npm start 
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - '3000:3000'
    tty: true
    stdin_open: true
    volumes:
      - './frontend/src/:/usr/src/mcc/frontend/src/'
      - './frontend/public/:/usr/src/mcc/frontend/public/'
      - './frontend/package.json:/usr/src/mcc/frontend/package.json'
      - './frontend/package.json:/usr/src/mcc/frontend/yarn.lock'
