# base image
FROM node:14.3.0-alpine

# set working directory
WORKDIR /usr/src/mcc/frontend

# install and cache app dependencies
COPY frontend/package.json .
COPY frontend/package-lock.json .
RUN npm install
RUN npm install @vue/cli@4.4.1 -g
COPY frontend/src/ ./src/
COPY frontend/public/ ./public/

# start app
CMD ["npm", "run", "serve"]
