# base image
FROM node:14.3.0-alpine

# set working directory
WORKDIR /usr/src/mcc/frontend

# add to PATH
ENV PATH /usr/src/mcc/frontend/node_modules/.bin:$PATH

# install and cache app dependencies
COPY frontend/package.json .
RUN npm install
RUN npm install react-scripts@3.4.1
COPY frontend/src/ ./src/
COPY frontend/public/ ./public/
