version: "3"

services:
  db:
    image: postgres

  web:
    build: 
      context: .
      dockerfile: Dockerfile.web
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - dev.env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    command: npm run serve
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - '8080:8080'
    tty: true
    stdin_open: true
    volumes:
      - './frontend/src/:/usr/src/mcc/frontend/src/'
      - './frontend/public/:/usr/src/mcc/frontend/public/'
      - './frontend/package.json:/usr/src/mcc/frontend/package.json'
      - './frontend/package-lock.json:/usr/src/mcc/frontend/package-lock.json'
      - './frontend/babel.config.js:/usr/src/mcc/frontend/babel.config.js'